spring.datasource.url=${CAMINHO_BANCO}
spring.datasource.username=${USERNAME_PG}
spring.datasource.password=${PASSWORD_PG}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET}

server.address=0.0.0.0
server.port=8080